### ISSUE TITLE
Missing images in includes

### ISSUE THREAD

**Issue by theecrit** [openoakland/funding-public-safety#56]
## Description

Images added via includes are broken (specifically, in the hero.njk and footer.njk includes):

- hero.njk uses the `.index-hero` class to designate a background image that isn't appearing.
- footer.njk displays properly on the home page (which uses the home.njk layout), but not on the other pages (which use the page.njk layout). This behavior is particularly weird, as I can't find any discrepancies between the footer inclusion in those two layouts.

I assume this has to do with the file pathing filters described in PR #55.

**Comment by aemann2** [comment]
Fixed in #65
