### ISSUE TITLE
Images squished on mobile

### ISSUE THREAD

**Issue by theecrit** [openoakland/funding-public-safety#57]
## Description

When viewed on mobile, images are squished disproportionately. Their width should shrink to fit the viewport but they should maintain their aspect ratios. There's at least one [11ty plugin](https://github.com/5t3ph/eleventy-plugin-social-images) that might help solve for this. 
![image](https://user-images.githubusercontent.com/32755410/149613111-b68fb735-c433-46b1-9b3d-1eaeeb9951e0.png)

**Comment by jaedoak** [comment]
The issue here is just that the class wasn't getting set on those images. Code has `class="class="card-img-top"`. Remove the extra `class="` and all is good.

I can push a fix, but I'm new to github projects - I'm not seeing how to assign or move an issue. I'm also new to forks, so I'll see if I can at least get a Pull Request queued up. :)

**Comment by aemann2** [comment]
> I can push a fix, but I'm new to github projects - I'm not seeing how to assign or move an issue. 

Hey @jaedoak, there's a link in the README for quick access to the board under the "Project management" section. Here's [the url](https://github.com/openoakland/funding-public-safety/projects/1). I went ahead and moved the issue to 'in progress' and assigned it to you.

**Comment by jaedoak** [comment]
Thank you! It seems that Jess needs to set me up as a contributor before I can do that for myself. Thanks for taking care of it -

**Comment by theecrit** [comment]
Ok, I don't want to merge this just yet because the build will break, I think, based on issues with the latest merge. @aemann2 is going to try troubleshooting those on Monday, and then I'll review/merge these css fixes. Thanks!
