### ISSUE TITLE
Get relative paths working for images

### ISSUE THREAD

**Issue by aemann2** [openoakland/funding-public-safety#66]
Currently, image paths in the /docs folder are being determined according to the assetPath front matter variable in each page's .md file.

A better solution would be to use a relative path to get to the assets folder, and navigate to that folder relative the root directory (/assets/images/...). The problem is, GitHub Pages has trouble with relative paths:

https://stackoverflow.com/questions/16316311/github-pages-and-relative-paths

https://github.com/openoakland/funding-public-safety/issues/51

I believe the solution might have to do with [URL filters](https://www.11ty.dev/docs/filters/url/) in Eleventy, but I can't get the syntax/config working right. 

Another potential solution would be to use a service like Netlify to host the site, which doesn't have this problem with relative paths.

**Comment by jaedoak** [comment]
I couldn't get the filters people shared on the Eleventy issue to work, but I did make something that does the trick like this:
`{{ 'assets/images/OpenOakland-logo-color-1000.png' | relative }}`

What do you think? Too clunky or good solution? (For the root index.html, it outputs `'assets/images/OpenOakland-logo-color-1000.png'` and for /about-funding-public-safety/index.html (for example) it outputs `'../assets/images/OpenOakland-logo-color-1000.png'`.

**Comment by aemann2** [comment]
@jaedoak that looks good to me...I think it's readable and definitely not as clunky as the solution we have in place now. 

Did you find documentation for that `| relative` trick, or did you just know about it? I feel like I went down a rabbit hole trying to get the filtering to work.

If you make a PR for this, I'll merge it! I need to make a 2nd PR afterward to take the relative links out of the front matter, but once we've done that we should be able to close this issue. Thanks!
