### ISSUE TITLE
Hamburger menu on mobile not expandable

### ISSUE THREAD

**Issue by theecrit** [openoakland/funding-public-safety#74]
## Description

The global nav menu collapses to a hamburger icon when the viewport shrinks, as expected. However, tapping on it is non-responsive, rendering navigation impossible on mobile. 

Tested with Firefox and Safari on iOS 14.8. 

This may be due to [Bootstrap nav implementation](https://getbootstrap.com/docs/5.1/components/navbar/) or possibly the superfluous [11ty nav plugin](https://www.11ty.dev/docs/plugins/navigation/) that isn't properly configured. We should be using one or the other.

**Comment by jaedoak** [comment]
@aemann2 FYI, I have a local fix for this -- let me know if it would be helpful. If you've already fixed this, ignore this comment. :)

**Comment by aemann2** [comment]
> @aemann2 FYI, I have a local fix for this -- let me know if it would be helpful. If you've already fixed this, ignore this comment. :)

If you want to open up a PR for this, that would be great!

**Comment by jaedoak** [comment]
I opened up a PR, but I've never worked with this kind of templating system before, so please double-check that I used the right approach! (I just modified the page and home files, and let `npm run build` take care of the *.html updates).

If I want to learn more about how you're building this site, what should I read up on? Nunjucks?

**Comment by theecrit** [comment]
@jaedoak So the nice thing about Eleventy is that you can use multiple templating frameworks: https://www.11ty.dev/docs/languages/
